steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tomis-ai:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tomis-ai:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud run deploy tomis-ai \
        --image gcr.io/$PROJECT_ID/tomis-ai:$SHORT_SHA \
        --region ${_REGION} \
        --platform managed \
        --allow-unauthenticated \
        --service-account ${_SERVICE_ACCOUNT} \
        --set-env-vars BUCKET_PUBLIC=${_BUCKET}
substitutions:
  _REGION: "europe-west1"
  _SERVICE_ACCOUNT: "tomis-tomisai-run@${PROJECT_ID}.iam.gserviceaccount.com"
  _BUCKET: "tomis-ai-public"  # înlocuiește dacă este nevoie
images:
- 'gcr.io/$PROJECT_ID/tomis-ai:$SHORT_SHA'
