steps:
# Build the image and push to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tomis-ai:$SHORT_SHA', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/tomis-ai:$SHORT_SHA' ]

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy tomis-ai \
        --image gcr.io/$PROJECT_ID/tomis-ai:$SHORT_SHA \
        --region ${_REGION} \
        --platform managed \
        --allow-unauthenticated \
        --service-account ${_SERVICE_ACCOUNT} \
        --set-secrets MAPS_KEY=${_MAPS_SECRET_NAME}:latest
# substitutions for deploy
substitutions:
  _REGION: "europe-west1"
  _SERVICE_ACCOUNT: "tomis-run-sa@${PROJECT_ID}.iam.gserviceaccount.com"
  # full secret resource names:
  # _MAPS_SECRET_NAME: "projects/PROJECT_ID/secrets/maps-api-key"
