steps:
# 1. Build the container image
# This step builds the Docker image using the Dockerfile in the current directory.
# The image is tagged with the project ID and the commit SHA to ensure uniqueness.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tomis-ai-backend:$COMMIT_SHA', '.']

# 2. Push the container image to Google Container Registry (GCR)
# This step pushes the tagged image to GCR, making it available for deployment.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tomis-ai-backend:$COMMIT_SHA']

# 3. Deploy the container image to Cloud Run
# This step deploys the image from GCR to a new or existing Cloud Run service.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    # Comanda principală pentru Cloud Run
    - 'run'
    - 'deploy'
    - 'tomis-ai-backend'
    
    # Imaginea specifică de deploy
    - '--image=gcr.io/$PROJECT_ID/tomis-ai-backend:$COMMIT_SHA'
    
    # Regiunea GCP (poate fi modificată)
    - '--region=us-central1'
    
    # Specificații de platformă
    - '--platform=managed'
    
    # Permite acces public (necesar pentru Front-end)
    - '--allow-unauthenticated'
    
    # Portul pe care ascultă containerul
    - '--port=8080'
    
    # SPECIFICĂ CONTUL DE SERVICIU DE RULARE PENTRU SERVICIUL CLOUD RUN
    # Acest Cont de Serviciu trebuie să aibă permisiuni GCS și Speech-to-Text.
    # Valoarea de mai jos este un placeholder; folosiți Contul de Serviciu real!
    - '--service-account=tomis-ai-service@ro-igpr-speech-to-text.iam.gserviceaccount.com' 

# Această secțiune specifică imaginile care sunt construite de acest pipeline.
images:
- 'gcr.io/$PROJECT_ID/tomis-ai-backend:$COMMIT_SHA'

# Secțiunea options: Rezolvarea erorii de logare și Contul de Serviciu
options:
  # Timpul maxim pentru build
  timeout: '1200s'
  
  # Tipul de mașină (pentru build-uri mai rapide)
  machineType: 'N1_HIGHCPU_8'
  
  # CONTUL DE SERVICIU PENTRU A RULA CLOUD BUILD-UL ÎN SINE
  # Acest cont declanșează și gestionează build-ul
  serviceAccount: projects/$PROJECT_NUMBER/serviceAccounts/tomis-ai-service@ro-igpr-speech-to-text.iam.gserviceaccount.com
  
  # REZOLVAREA ERORII: Specifică să folosească doar jurnalele Cloud Logging
  logging: CLOUD_LOGGING_ONLY
